### ISSUE TITLE
Add emacs-hide-mode-line to GNU ELPA

### ISSUE THREAD

**Issue by skangas** [hlissner/emacs-hide-mode-line#8]
Hi,

Would you consider adding this package to [GNU ELPA](https://elpa.gnu.org/)? That would have some advantages, for example it would give a realistic way to get shipped with GNU Emacs in the future. There seem to be only one contributor, so we would only need you to sign the copyright assignment (and then ensure future contributors also sign them).

Otherwise, there is always the alternative of adding it to [NonGNU ELPA](https://elpa.nongnu.org/).

**Comment by hlissner** [comment]
Sorry to say, but I'd rather not, due to time constraints. I'm not familiar enough with either archive, their rules, or mailing lists as a format, and I'm spread too thin these days to give it the attention it deserves, much less offer user support that might arise from it. I have copyright assignment already, but I'm not keen on policing that for potential future contributors for such a trivial package, nor am I interested in including it in Emacs (if that were even possible).

That said, if others want to submit it on my behalf, they may do so, but it's already on MELPA, which is enough for me.
